### ISSUE TITLE
Add a webview and user interactions for improvements

### ISSUE THREAD

**Issue by Alchez** [revant/erpnext_feature_board#19]
- Web view (also allowed for Guest users)
	- show paginated Improvement list
	- on Improvement Form show PR url, status, and site name.
	- add a form/popup to initiate a "Moderation Request" referencing Improvement
	- keep track of "Moderation Request" by user on the form view

- Webhooks
	- Required for automation after github PR is updated and developer fixes code after user review
	- Webhooks also adds "Moderation Request", to upgrade
	- Open PR and PR with active sites only, add "Moderation Request" on change of PR (commits, force-push)

- "Moderation Request" Types
	- Initiate site for improvement
	- Upgrade site for improvement
	- Delete site for improvement
	- Add user (and set roles) in site for Improvement (use admin password)

- Moderators can:
	- Respond to "Moderation Request", "act" on it or "deny/close"
	- Add user and set roles for the sites generated for PR
	- Trigger builds for PR
	- Trigger updated after PR is updated
	- Trigger tear down, if site generation results in Error, or PR is merged.
	- check error logs and report

- Add moderator on invite
	- share invitation link, expires in configurable time
	- Filter by Domain
	- Access Improvements by domain

Rename "Moderation Request" to something more meaningful.

**Comment by revant** [comment]
moving to forum

https://discuss.erpnext.com/t/help-us-build-the-pr-review-system/76785
