### ISSUE TITLE
github delete merged Improvement(s)

### ISSUE THREAD

**Issue by revant** [revant/erpnext_feature_board#28]
Cron to delete merged improvements
- Queue site Delete first
- Once site is deleted, Delete the improvement and related Review requests

**Comment by Alchez** [comment]
There's 3 statuses to deal with:

- Open: we don't have to do anything here
- Merged: take actions as in this issue
- Closed: should we also delete sites here? or queue it up a bit later? in case of accidental closes?

**Comment by revant** [comment]
> Closed: should we also delete sites here? or queue it up a bit later? in case of accidental closes?

We should delete. Assuming accidental closes are re-opened within 1 hour.
